# Exercise 5A: NumPy Fundamentals
This notebook covers the basics of NumPy arrays including creation, 
data types, indexing, slicing, and multi-dimensional arrays.

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [4]:
print(arr_1.dtype)
# U = Unicode string
# 6 = max number of characters in the strings
# cherry has 6 characters so dtype is U6

<U6


In [5]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [7]:
print(arr_2)
# No! .T returns a transposed view but does not change the original arr_2

[[10 11 12]
 [13 14 15]]


In [8]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
# arr_3[0, 2] = row 0, column 2 = value 5
# arr_3[1, 1] = row 1, column 1 = value 4
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [10]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
