# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
# Create arrA as a 2D array
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
# Loop through the first dimension of arrA
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
# Loop through the second dimension of arrA
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through each row in arrA and prints the entire row multiplied by 2, so it outputs two arrays.The second loop goes one level deeper, iterating through each element within the rows and printing each value multiplied by 2, resulting in six individual numbers.

In [5]:
# Loop through second dimension and assign x*2 to loop_result
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)
# loop_result stores x*2 (the entire row multiplied by 2) not y*2
# x is the full row, y is each individual element

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [6]:
# Concatenate arrA with arrA on axis=0 (default)
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
# Concatenate arrA with arrA on axis=1
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
# Stack joined_array_1 with joined_array_1 on default axis
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
# Stack joined_array_1 with joined_array_2 on default axis
try:
    stacked_array_2 = np.stack((joined_array_1, joined_array_2))
    print(stacked_array_2)
except ValueError as e:
    print(f'Error: {e}')
# Error occurs because joined_array_1 and joined_array_2 have different shapes
# np.stack() requires all input arrays to have the same shape

Error: all input arrays must have the same shape


In [10]:
# Concatenate joined_array_1 with arrA
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
# Concatenate joined_array_1 with arrA on axis=1
try:
    another_2 = np.concatenate((joined_array_1, arrA), axis=1)
    print(another_2)
except ValueError as e:
    print(f'Error: {e}')
# Error occurs because joined_array_1 has 4 rows and arrA has only 2 rows
# When joining on axis=1 the number of rows must match

Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2


In [12]:
# hstack - stacks horizontally (adds columns)
hstacked = np.hstack((arrA, arrA))
print('hstack:')
print(hstacked)

# vstack - stacks vertically (adds rows)
vstacked = np.vstack((arrA, arrA))
print('vstack:')
print(vstacked)

# dstack - stacks depth-wise (adds a third dimension)
dstacked = np.dstack((arrA, arrA))
print('dstack:')
print(dstacked)

hstack:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
vstack:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
dstack:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


 ## Splitting Arrays

In [13]:
# Split joined_array_1 into 2
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# Result: 2 arrays, each with 2 rows and 3 columns (2D arrays)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [14]:
# Split joined_array_1 into 3
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Result: 3 arrays — first two have 2 rows, last one has 0 rows
# joined_array_1 has 4 rows so it can't split evenly into 3

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [15]:
# Use where() to find even numbers in arrA
# If even print the value, if odd print 'odd'
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [17]:
# Create arrB as a 2D array
arrB = np.array([(7, 6), (13, 5), (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [18]:
# Print arrB first
print(arrB)

# Filter values less than 7
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]
