# Exercise 1.B NumPy Random

In [1]:
import numpy as np

 ## Generating Random Numbers

In [2]:
# Random set of integers between 1 and 20 with size of 2 elements
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[15 18]


In [3]:
# Random set of integers between 1 and 20 with size of 1 row, 2 columns
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[17  7]]


In [4]:
# Random set of floats between 0 and 1 with size of 2 rows, 1 column
r_3 = np.random.random(size=(2, 1))
print(r_3)

[[0.38867991]
 [0.80696054]]


In [5]:
# Random set of integers between 20 and 100 with size of 4 rows, 5 columns
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[79 83 98 50 31]
 [85 21 43 42 44]
 [77 81 35 20 72]
 [76 52 41 58 30]]


In [6]:
# Random set of floats between 0 and 1 with size of 4 rows, 5 columns
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.23277658 0.61208092 0.26463238 0.85739376 0.69109577]
 [0.14091639 0.67414623 0.76125735 0.66225289 0.21209715]
 [0.81982071 0.41496632 0.64732842 0.11060751 0.89464811]
 [0.08784224 0.84231455 0.32951081 0.63759786 0.36594654]]


## Generating Random Choices from an Array

In [9]:
# Create a 1D array of 12 classmate names
students = np.array(['Sayed', 'Sahar', 'luis', 'Priya', 'Jordan', 
                     'samia', 'hana', 'dagi', 'Grace', 'Ken', 
                     'JB', 'charles'])
print(students)

['Sayed' 'Sahar' 'luis' 'Priya' 'Jordan' 'samia' 'hana' 'dagi' 'Grace'
 'Ken' 'JB' 'charles']


In [10]:
# Choose one random selection from students
call_on = np.random.choice(students)
print(call_on)

dagi


In [11]:
# Choose random sampling from students - 3 rows, 4 columns
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# This would NOT be an effective way to assign breakout groups because
# np.random.choice() allows repeats by default — the same student
# could appear in multiple groups at the same time!
# A better approach would be to use np.random.shuffle() instead


[['luis' 'luis' 'Priya' 'charles']
 ['Sayed' 'Ken' 'Sayed' 'JB']
 ['Sahar' 'Grace' 'Sahar' 'Grace']]


In [12]:
# Choose 5 random selections with different probability values
call_on_weighted = np.random.choice(students, size=5, p=[
    0.30,  # Sayed - 30% chance
    0.10,  # Sahar - 10% chance
    0.10,  # luis - 10% chance
    0.10,  # Priya - 10% chance
    0.10,  # Jordan - 10% chance
    0.05,  # samia - 5% chance
    0.05,  # hana - 5% chance
    0.05,  # dagi - 5% chance
    0.05,  # Grace - 5% chance
    0.05,  # Ken - 5% chance
    0.00,  # JB - 0% chance (will never be called on)
    0.05   # charles - 5% chance
])
print(call_on_weighted)
# p values must add up to exactly 1.0 (100%)
# JB has 0% so will never be selected
# Sayed has 30% so is most likely to be called on


['Sayed' 'Sayed' 'luis' 'luis' 'Sayed']


## Generating a Normal Distribution

In [13]:
# Random normal distribution
# mean=10, standard deviation=5, size=4 rows x 5 columns
bell_curve = np.random.normal(10, 5, size=(4, 5))
print(bell_curve)

[[ 7.7730641   6.776017   15.29716951 15.5478609  11.91869424]
 [13.39861464 11.22343598 12.64995023 12.16226615  7.24781486]
 [ 9.62575873 17.35585707 15.50007407  3.94646391 10.77413511]
 [17.13619939  9.60644825  8.23869332 10.97909975  6.81183627]]
