# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

print('r_1:', r_1)
print('r_2:', r_2)
print('r_3:', r_3)
print('r_4:', r_4)
print('r_5:', r_5)

r_1: [13 17]
r_2: [[15  4]]
r_3: [[0.65894778]
 [0.63987537]]
r_4: [[32 59 29 29 29]
 [83 49 73 98 85]
 [93 44 35 76 47]
 [79 96 56 27 49]]
r_5: [[0.40014778 0.17953099 0.20469761 0.48127357 0.69121853]
 [0.053823   0.77785381 0.24659158 0.03259107 0.99962722]
 [0.63990866 0.09990559 0.0402577  0.649613   0.79459204]
 [0.98026455 0.99367006 0.74163851 0.44314801 0.4672437 ]]


## Permutations

In [3]:
print(r_4)

[[32 59 29 29 29]
 [83 49 73 98 85]
 [93 44 35 76 47]
 [79 96 56 27 49]]


In [4]:
np.random.shuffle(r_4)
print(r_4)
# shuffle() rearranges the ROWS of the array randomly
# but keeps each row intact — elements within each row stay in the same order

[[83 49 73 98 85]
 [93 44 35 76 47]
 [32 59 29 29 29]
 [79 96 56 27 49]]


The shuffle function rearranged the rows of r_4 randomly but kept the elements within each row in the same order. Only the row positions changed, not the individual values inside each row.

In [5]:
new_shuffle = np.random.permutation(r_4)
print('new_shuffle:')
print(new_shuffle)
print('r_4 after permutation:')
print(r_4)
# permutation() returns a NEW shuffled array without changing the original
# shuffle() changes the original array in place

new_shuffle:
[[83 49 73 98 85]
 [93 44 35 76 47]
 [79 96 56 27 49]
 [32 59 29 29 29]]
r_4 after permutation:
[[83 49 73 98 85]
 [93 44 35 76 47]
 [32 59 29 29 29]
 [79 96 56 27 49]]


Use shuffle() when you want to rearrange the original array permanently. Use permutation() when you want a shuffled copy but need to keep the original array unchanged.

## Mathematical Operations

In [6]:
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_2:', r_2, '| shape:', r_2.shape)
result = np.add(r_1, r_2)
print('r_1 + r_2:', result)
print('shape:', result.shape)

r_1: [13 17] | shape: (2,)
r_2: [[15  4]] | shape: (1, 2)
r_1 + r_2: [[28 21]]
shape: (1, 2)


In [7]:
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_3:', r_3, '| shape:', r_3.shape)
result = np.add(r_1, r_3)
print('r_1 + r_3:', result)
print('shape:', result.shape)

r_1: [13 17] | shape: (2,)
r_3: [[0.65894778]
 [0.63987537]] | shape: (2, 1)
r_1 + r_3: [[13.65894778 17.65894778]
 [13.63987537 17.63987537]]
shape: (2, 2)


In [8]:
print('r_2:', r_2, '| shape:', r_2.shape)
print('r_4:', r_4, '| shape:', r_4.shape)
result = np.add(r_2, r_4)
print('r_2 + r_4:', result)
print('shape:', result.shape)

r_2: [[15  4]] | shape: (1, 2)
r_4: [[83 49 73 98 85]
 [93 44 35 76 47]
 [32 59 29 29 29]
 [79 96 56 27 49]] | shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [9]:
try:
    print(np.add(r_1, r_4))
except ValueError as e:
    print(f'r_1 + r_4 Error: {e}')

try:
    print(np.add(r_2, r_4))
except ValueError as e:
    print(f'r_2 + r_4 Error: {e}')

try:
    print(np.add(r_3, r_4))
except ValueError as e:
    print(f'r_3 + r_4 Error: {e}')
# r_1 has shape (2,) and r_4 has shape (4,5) — not compatible
# r_3 has shape (2,1) and r_4 has shape (4,5) — not compatible

r_1 + r_4 Error: operands could not be broadcast together with shapes (2,) (4,5) 
r_2 + r_4 Error: operands could not be broadcast together with shapes (1,2) (4,5) 
r_3 + r_4 Error: operands could not be broadcast together with shapes (2,1) (4,5) 


In [10]:
print(np.add(np.array([1]), r_4))
# adds 1 to every element in r_4

[[84 50 74 99 86]
 [94 45 36 77 48]
 [33 60 30 30 30]
 [80 97 57 28 50]]


In [11]:
print(np.add(np.array([[1]]), r_4))
# adds 1 to every element in r_4 — same result as above

[[84 50 74 99 86]
 [94 45 36 77 48]
 [33 60 30 30 30]
 [80 97 57 28 50]]


In [12]:
print(np.add(np.array([1,1,1,1,1]), r_4))
# adds 1 to each column of every row in r_4

[[84 50 74 99 86]
 [94 45 36 77 48]
 [33 60 30 30 30]
 [80 97 57 28 50]]


In [13]:
try:
    print(np.add(np.array([[1],[1]]), r_4))
except ValueError as e:
    print(f'Error: {e}')
# Error: shape (2,1) cannot broadcast with shape (4,5)
# 2 rows cannot broadcast to 4 rows

Error: operands could not be broadcast together with shapes (2,1) (4,5) 


Broadcasting allows NumPy to add arrays of different shapes by stretching the smaller array to match the larger one. A single value gets added to every element. A row of values gets added to each matching column across all rows. The shape of the result matches the larger array. Broadcasting only works when the dimensions are compatible — either equal or one of them is 1.

## Rounding

In [14]:
print(r_3)

[[0.65894778]
 [0.63987537]]


In [15]:
print(np.trunc(r_3))
# trunc cuts off the decimal — always toward zero

[[0.]
 [0.]]


In [16]:
print(np.fix(r_3))
# fix works like trunc — rounds toward zero

[[0.]
 [0.]]


In [17]:
print(np.floor(r_3))
# floor always rounds DOWN to nearest integer

[[0.]
 [0.]]


In [18]:
print(np.ceil(r_3))
# ceil always rounds UP to nearest integer

[[1.]
 [1.]]


In [19]:
print(np.round(r_3, 2))
# round rounds to 2 decimal places

[[0.66]
 [0.64]]


## Cumulative Operations

In [20]:
print(r_4)

[[83 49 73 98 85]
 [93 44 35 76 47]
 [32 59 29 29 29]
 [79 96 56 27 49]]


In [21]:
print(np.sum(r_4))

1168


In [22]:
print(np.sum(r_4, axis=0))
# sums each column across all rows

[287 248 193 230 210]


In [23]:
print(np.sum(r_4, axis=1))
# sums each row across all columns

[388 295 178 307]


In [24]:
print(np.cumsum(r_4))
# rolling total of all values flattened

[  83  132  205  303  388  481  525  560  636  683  715  774  803  832
  861  940 1036 1092 1119 1168]


In [25]:
print(np.cumsum(r_4, axis=0))
# rolling total down each column

[[ 83  49  73  98  85]
 [176  93 108 174 132]
 [208 152 137 203 161]
 [287 248 193 230 210]]


## Grocery Problem

In [26]:
# bag1: 2 vegetables, 3 fruits, 4 snacks, 0 beverages
# bag2: 4 vegetables, 0 fruits, 1 snack, 2 beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print('bag1:', bag1)
print('bag2:', bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [27]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)
print(f'The first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [28]:
totals = np.add(bag1, bag2)
print(f'There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [29]:
ali = np.array([5, 4, 6, 4, 2])